title: Ojas Milk Products
author: OjasAgro Pvt Ltd.
email: ojasagro@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ojas Ojas Ojas Ojas

#baseurl: "/ojas/" # the subpath of your site, e.g. /blog/
#url: "https://ojsg.z29.web.core.windows.net" # the base hostname & protocol for your site

twitter_username: ojasdiary


sass:
    style: compressed
